import { Button } from "std-widgets.slint";

export component ExpenseTab inherits Rectangle {
    x: 100px;
    background: gray;

    callback load_file();

    VerticalLayout {
        HorizontalLayout {
            height: 100px;
            Text {
                text: "Total Expenses";
            }
            Button {
                width: 100px;
                height: 60px;
                text: "Add Expense";

                clicked => {
                    load_file();
                }
            }
        }
    }
}
