[package]
name = "Doflamingo"
version = "0.1.0"
authors = ["Sadaananth Anbucheliyan <ananth.anbucheliyan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf-extract = "0.7.10"
