import { Date, DatePickerPopup, Button, VerticalBox } from "std-widgets.slint";

export component DateText inherits Rectangle {
    in-out property <string> date_selected: date_text.text;

    Rectangle {
        height: 60px;
        date_text := TextInput {
            width: 60px;
            height: 60px;
            text: "DD/MM/YYYY";
        }
        TouchArea {
            clicked => {
                date_picker.show();
            }
        }
    }
    date-picker := DatePickerPopup {
        visible: false;

        // x:  date_text.x + date-text.width;
        // y: date-text.y;
       
        width: 360px;
        height: 524px;
        close-policy: PopupClosePolicy.no-auto-close;
        title: "Select the date of Salary";
        date: { year: 2024, month:11};

        accepted(date) => {
            date-picker.close();
            date_text.text = date.day + "//" + date.month + "//" + date.year;
        }
    }
}
