load("@rules_cc//cc:defs.bzl", "cc_library")

cc_binary(
    name = "BankStatementParser",
    srcs = [
        "main.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@SadaLogger",
    ],
)
