import { Date, DatePickerPopup, Button, VerticalBox } from "std-widgets.slint";
import {DebtTab} from "debt.slint";
import {SalaryTab} from "salary.slint";
import {HomeView} from "home.slint";

export global Data {
    in-out property <int> today: 23;
    in-out property <int> this_month: 12;
    in-out property <int> this_year: 2001;
}

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;

    callback add_salary(string, int);
    callback add_debt(string, string, string, string, string);

    salary := SalaryTab {
        visible: false;

        add_salary(date_set, salary_set) => {
            root.add_salary(date_set, salary_set);
        }
    }

    debt := DebtTab {
        visible: false;
        add_debt(start_date, end_date, amount, interest, description) => {
            root.add_debt(start-date, end-date, amount, interest, description);
        }
    }

    homeview := HomeView {
        enter_salary => {
            self.visible = false;
            salary.visible = true;
        }

        enter_debt => {
            self.visible = false;
            debt.visible =  true;
        }
    }
}
