import { DatePickerPopup, Button, VerticalBox } from "std-widgets.slint";

component SalaryTab inherits Rectangle {
    width: 800px;
    height: 600px;

    date-picker := DatePickerPopup {
        width: 360px;
        height: 524px;
        close-on-click: false;
        title: "Select the date of Salary";
        // TODO: Set starting date

        accepted(date) => {
            date-picker.close();
            date_text.text = "closed";
        }
    }

    HorizontalLayout {
        Rectangle {
            height: 60px;
            date_text := TextInput {
                width: 60px;
                height: 60px;
                text: "DD/MM/YYYY";
            }
            TouchArea {
                clicked => {
                    date_picker.show();
                }
            }
        }

        amount := TextInput {
            height: 60px;
            text: "Amount";
        }

        add := Button {
            height: 60px;
            text: "Add";
        }
    }
}

component HomeView inherits Rectangle {
    width: 800px;
    height: 600px;

    callback enter_salary();

    Button {
        width: 100px;
        height: 50px;
        text: "Enter Salary";

        clicked => {
            parent.enter_salary();
        }
    }
}

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;

    salary := SalaryTab {
        visible: false;
    }

    homeview := HomeView {
        enter_salary => {
            self.visible = false;
            salary.visible = true;
        }
    }
}
