import { Date, DatePickerPopup, Button, VerticalBox } from "std-widgets.slint";
import {DebtTab} from "pages/debt.slint";
import {SalaryTab} from "pages/salary.slint";
import {OverviewTab} from "pages/overview.slint";
import {AboutTab} from "pages/about.slint";
import {HomeView} from "pages/home.slint";

export global Data {
    in-out property <int> today: 23;
    in-out property <int> this_month: 12;
    in-out property <int> this_year: 2001;
}

export component AppWindow inherits Window {
    width: 1080px;
    height: 720px;
    title: "Doflamingo Finance";

    callback add_salary(string, int);
    callback add_debt(string, string, string, string, string);
    pure callback render_plot(/* pitch */ float, /* yaw */ float, /* amplitude */ float) -> image;

    overview := OverviewTab {
        visible: true;
    }

    salary := SalaryTab {
        visible: false;

        add_salary(date_set, salary_set) => {
            root.add_salary(date_set, salary_set);
        }
    }

    debt := DebtTab {
        visible: false;
        add_debt(start_date, end_date, amount, interest, description) => {
            debug("Adding debt");
            root.add_debt(start-date, end-date, amount, interest, description);
        }
        render_plot(pitch, yaw, amplitude) => {
            root.render_plot(pitch, yaw, amplitude);
        }
    }

    about := AboutTab {
        visible: false;
    }

    homeview := HomeView {
        enter_overview => {
            overview.visible = true;
            salary.visible = false;
            debt.visible = false;
            about.visible = false;
        }
        enter_salary => {
            salary.visible = true;
            overview.visible = false;
            debt.visible = false;
            about.visible = false;
        }
        enter_debt => {
            debt.visible = true;
            salary.visible = false;
            overview.visible = false;
            about.visible = false;
        }
        enter_about => {
            about.visible = true;
            salary.visible = false;
            overview.visible = false;
            debt.visible = false;
        }
    }
}
