import { Button } from "std-widgets.slint";

export component HomeView inherits Rectangle {
    width: 800px;
    height: 600px;

    callback enter_salary();
    callback enter_debt();

    GridLayout {
        spacing: 100px;
        Button {
            width: 100px;
            height: 100px;
            text: "Enter Salary";

            clicked => {
                root.enter_salary();
            }
        }
        Button {
            width: 100px;
            height: 100px;
            text: "Debt";

            clicked => {
                root.enter_debt();
            }
        }
    }
}
